markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Shi Yan
production_url : http://shi-yan.github.io
description: "Random."
disqus_shortname: caarlos0blog
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Shi Yan
  github : shi-yan
  twitter : notwitter
  email: noemail@gmail.com
