# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		Shi Yan
tagline:	'blog'
description:	'My personal blog.'
url:		http://shi-yan.github.io
commentsystem:	google
disqus:		example

author:
  name:		'Shi Yan'
  url:		https://plus.google.com/115320226384446129864

paginate:	10

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	github
    url:	https://github.com/camporez
    desc:	Fork me on github
    
menu:
  - title:	Home
    url:	/
    
copyright:
  author:	Shi Yan
  url:		http://camporez.com
  type_title:	Some rights reserved
  type_url:

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
